watchlist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('', RedirectView.as_view(url='watchlist/dashboard/', permanent=False)),
    path('sidebar_ajax/<int:movie_id>/', sidebar_ajax, name='sidebar_ajax'),
    path('sidebar_actor_ajax/<int:actor_id>/', sidebar_actor_ajax, name='sidebar_actor_ajax'),
    path('modal_ajax/<int:movie_id>/', modal_ajax, name='modal_ajax'),
    path('get_random_movies/', get_random_movies, name='get_random_movies'),
    path('poster_update/', poster_update, name='poster_update'),
    path('get_movie_info/', get_movie_info, name='get_movie_info'),
    path('elo_matchup/', elo_matchup, name='elo_matchup'),
    path('save_poster_link/', save_poster_link, name='save_poster_link'),
    path('watchlist/dashboard/', DashboardView.as_view(), name='dashboard'),
    path('watchlist/watchlog/', WatchlogView.as_view(), name='watchlog'),
    path('watchlist/watchlist/', WatchlistView.as_view(), name='watchlist'),
    path('watchlist/rankings/', RankingsView.as_view(), name='rankings'),
    path('watchlist/elo/', EloView.as_view(), name='elo'),
    path('watchlist/update_order/', update_order, name='update_order'),
    # Add other URLs for watchlog, watchlist, rankings, elo, etc.
]

watchlist/forms.py
from django import forms

SERVICES = [
    ('', ' '),  # Empty choice for the default/placeholder
    ('Netflix', 'Netflix'),
    ('Hulu', 'Hulu'),
    ('Max', 'Max'),
    ('Disney Plus', 'Disney Plus'),
    ('Apple TV Plus', 'Apple TV Plus'),
    ('Amazon Prime Video', 'Amazon Prime Video'),
    ('Peacock Premium', 'Peacock Premium'),
    ('Paramount Plus', 'Paramount Plus'),
    ('Paramount+ Amazon Channel', 'Paramount+ Amazon Channel'),
    ('Tubi TV', 'Tubi TV'),
    ('Freevee', 'Freevee'),
    ('TNT', 'TNT'),
    ('TBS', 'TBS'),
    ('AMC+', 'AMC+'),
    ('MGM Plus', 'MGM Plus'),
    ('Starz', 'Starz'),
    ('Youtube', 'Youtube'),
    ('Youtube Movies', 'Youtube Movies'),
    ('Tik Tok', 'Tik Tok'),
]

class MovieForm(forms.Form):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))
    year = forms.IntegerField(label='Year', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))
    rating = forms.FloatField(label='Rating', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}), required=False)
    review = forms.CharField(label='Review', widget=forms.Textarea(attrs={'class': 'form-control input rounded-1 dark-input'}), required=False)
    date_watched = forms.DateField(label='Date Watched', required=False)
    service = forms.ChoiceField(label="Service", choices=SERVICES, required=False)
    theaters = forms.BooleanField(label = "Theater", required=False)
    favorite = forms.BooleanField(label = "Favorite", required=False)
    tags = forms.CharField(label='Tags', required=False)

class WatchlistForm(forms.Form):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))
    year = forms.IntegerField(label='Year', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))
    date_added = forms.DateField(label='Date Added')
    favorite = forms.BooleanField(label = "Favorite", required=False)
    tags = forms.CharField(label='Tags', required=False)

class RankingForm(forms.Form):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))
    year = forms.IntegerField(label='Year', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))

class PosterForm(forms.Form):
    TMDB_ID = forms.CharField(label='TMDB ID', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))
    posterLink = forms.CharField(label='Poster', widget=forms.TextInput(attrs={'class': 'form-control input rounded-1 dark-input'}))

watchlist/templates/watchlist/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}CineMax'D{% endblock %}</title>

        {# External Stylesheets #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'watchlist/css/offcanvas.css' %}">
        <link rel="stylesheet" href="{% static 'watchlist/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'watchlist/css/tags.css' %}">

        {# Additional CSS Block #}
        {% block css %}{% endblock %}

        {# Favicon #}
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'watchlist/favicon.ico' %}">

        {# JS Libraries #}
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'watchlist/js/standard.js' %}"></script>
    </head>
    <body data-bs-theme="dark" class="bg-dark-subtle">
        {# Navbar #}
        <nav id="navbar" class="navbar sticky-top navbar-expand-lg py-1 bg-black shadow-lg">

            {# Brand Logo #}
            <div class="d-flex flex-wrap me-auto">
                <a href="/" class="d-flex navbar-brand align-items-center ms-3 mb-3 mb-lg-0 me-lg-auto text-decoration-none">
                    <img src="{% static 'watchlist/images/site-logo-h.png' %}" height="40px" alt="Bootstrap">
                </a>
            </div>

            {# Stats Bar #}
            <div id="statbar" class="hstack gap-3 py-2">
                {% for stat_key, stat_label, stat_value in stat_data %}
                    <div class="p-2 text-center">
                        <small class="h6 heading-stats">{{ stat_value|default:0 }}</small>
                        <small>{{ stat_label }}</small>
                    </div>
                    {% if not forloop.last %}
                        <div class="vr"></div>
                    {% endif %}
                {% endfor %}
            </div>

            {# Nav Links #}
            <ul class="nav nav-pills tiny nav-item nav-fill ms-auto">
                {% with current_url=request.path %}
                    {% for link, icon, text in navigation_links %}
                        <li class="nav-item px-2">
                            <a href="{% url link %}" class="nav-link{% if current_url == '/watchlist/'|add:link|add:'/' %} active{% endif %} rounded-5 raleway">
                                <div class="row">
                                    <div class="col d-flex align-items-center pe-1">
                                        <i class="bi nav-icon {{ icon }}"></i>
                                    </div>
                                    <div class="col d-flex align-items-center ps-0">
                                        <span class="nav-text text-center">{{ text }}<span>
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                {% endwith %}
            </ul>
        </nav>

        {# Content Block #}
        {% block content %}{% endblock %}

        {# Offcanvas Sidebar Container #}
        <div id="sidebarContainer"></div>
        <div id="modalContainer"></div>

        {# Additional JS Block #}
        {% block js %}{% endblock %}
    </body>
</html>

watchlist/templates/watchlist/elo.html
{% extends 'watchlist/base.html' %}
{% load static %}
{% load custom_filters %}
{% block js %}
    <script src="{% static 'watchlist/js/elo.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div id="eloContainer" class="row g-3">
            {% include "./eloMatchup.html" %}
        </div>
    </div>
{% endblock %}

watchlist/templates/watchlist/eloMatchup.html
{% load static %}
{% load custom_filters %}

<div class="card">
    {{ matches }} total matches since Jan. 29, 2024
</div>
<div class="row g-2">
    {% for movie in movies %}
        <div class="col-md-6">            
            {% if forloop.first %}            
                {% include "./elements/big-card-mirrored.html" with movie=movie %}
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            {% else %}
                {% include "./elements/big-card.html" with movie=movie %}
                <div class="d-grid gap-2 d-md-flex justify-content-md-start">
            {% endif %}
                <button class="z-2 btn btn-secondary border border-2 rounded-pill roboto mt-3" id="{{ movie.TMDB_ID }}" type="submit">
                {{ movie.title }} ({{ movie.year }}) [<b class="text-body-primary">{{ movie.elo }}</b>]
                </button>
            </div>
        </div>
    {% endfor %}
</div>

watchlist/templates/watchlist/modal_posters.html
{% load custom_filters %}
{% load static %}
<script src="{% static 'watchlist/js/modal.js' %}"></script>

<div id="{{ movie.TMDB_ID }}-modal" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">
                    <span class="movie-title">{{ movie.title }}</span> Posters
                </h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row g-3">
                    {% for poster in posters %}
                        <div class="col-md-3">
                            <img class="image-select poster rounded-3 border border-3" src="{{ poster }}" width="100%">
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger roboto" data-bs-dismiss="modal">Close</button>
                <button type="button" data-movie-id="{{movie.TMDB_ID}}" class="btn btn-secondary roboto" id="modalSubmit">
                    <span>
                        <div id="modalSubmitText">
                            Save Poster
                        </div>
                        <div class="d-none" id="modalSpinner">
                            <span>
                                <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
                                <span role="status">Loading...</span>
                            </span>
                        </div>
                    </span>
                </button>
            </div>
        </div>
    </div>
</div>

watchlist/templates/watchlist/watchlist-table.html
{% load static %}
{% load custom_filters %}

{% block js %}
    <script src="{% static 'watchlist/js/watchlist-datatable.js' %}"></script>
    <link rel="stylesheet" href="{% static 'watchlist/css/table.css' %}">
{% endblock %}

<div class="card rounded-4 mb-3">
    <table id="watchlist" class="table-sm table-borderless roboto" width="100%">
        <thead>
            <th width="3%"></th> {# 3% #}
            <th width="15%">Title</th> {# 18% #}
            <th width="3%" class="text-center">Year</th> {# 21% #}
            <th width="3%" class="text-center"></th> {# 24% #}
            <th width="3%" class="text-center">Fav</th> {# 27% #}
            <th width="10%" class="text-center">Tags</th> {# 37% #}
            <th width="5%" class="text-center">Runtime</th> {# 42% #}
            <th width="7%" class="text-center">Added</th> {# 49% #}
            <th width="7%" class="text-center">Released</th> {# 56% #}
            <th width="5%" class="text-center">Decade</th> {# 61% #}
            <th width="5%" class="text-center">MPA</th> {# 66% #}
            <th width="4%" class="text-center"> {# 70% #}
                <img class="align-top border border-3 border-secondary-subtle border-tertiary rounded-4 shadow-lg" src={% static 'watchlist/images/imdb_logo.png' %} height="20px">
            </th> 
            <th width="4%" class="text-center"> {# 74% #}
                <img class="align-top border border-3 border-secondary-subtle border-tertiary rounded-4 shadow-lg" src={% static 'watchlist/images/tmdb_logo.png' %} height="20px">
            </th>
            <th width="4%" class="text-center"> {# 78% #}
                <img class="align-top border border-3 border-secondary-subtle border-tertiary rounded-4 shadow-lg" src={% static 'watchlist/images/mc_logo.png' %} height="20px">
            </th>
            <th width="4%" class="text-center"> {# 82% #}
                <img class="align-top border border-3 border-secondary-subtle border-tertiary rounded-4 shadow-lg" src={% static 'watchlist/images/rtcritic_logo.png' %} height="20px">
            </th>
            <th width="4%" class="text-center"> {# 86% #}
                <img class="align-top border border-3 border-secondary-subtle border-tertiary rounded-4 shadow-lg" src={% static 'watchlist/images/rtuser_logo.png' %} height="20px">
            </th>
            <th width="4%" class="text-center"> {# 90% #}
                <img class="align-top border border-3 border-secondary-subtle border-tertiary rounded-4 shadow-lg" src={% static 'watchlist/images/lbxd_logo.png' %} height="20px">
            </th>
            <th width="6%" class="text-center">Avg</th> {# 96% #}
            <th width="4%" class="text-center">Oscar</th> {# 100% #}
            
            <th>Cast</th>
            <th>Director</th>
            <th>Genres</th>
            <th>Production Companies</th>
            <th>Providers</th>
        </thead>
        {% for instance in data %}
            <tr>
                {# Poster #}
                <td>
                    <img class="poster rounded-1 border border-2" src="{{ instance.posterLink }}" width="100%">
                </td>

                {# Title #}
                <td>
                    <a class="movie-title" data-movie-id="{{ instance.TMDB_ID }}" role="button" style="cursor: pointer;">
                        {{ instance.title }}
                    </a>
                </td>

                {# Year #}
                <td class="text-center">{{ instance.year }}</td>

                {# Service #}
                <td class="text-center">
                    {% if instance.provider.all %}
                        <img class="align-top border border-3 border-secondary-subtle border-tertiary rounded-4 shadow-lg" src="/static/watchlist/images/{{ instance.provider.first.name|striptags }}.png" height="24px">
                    {% endif %}
                </td>

                {# Favorite #}
                <td class="text-center align-middle">
                    {% if instance.favorite %}
                        <i class="bi bi-star-fill text-danger"></i>
                    {% endif %}
                </td>

                {# Tags #}
                <td class="text-center align-middle">
                    {% if instance.tags.all %}
                        {% for tag in instance.tags.all %}
                            {% include "./elements/tag-badge.html" with name=tag.name|process_badge %}
                        {% endfor %}
                    {% endif %}
                </td>

                {# Runtime #}
                <td class="text-center align-middle">
                    {% if instance.runtime %}
                        {% include "./elements/badge-secondary.html" with text=instance.runtime|convert_to_hrs fw="normal" mb="0" %}
                    {% endif %}
                </td>

                {# Date Seen #}
                <td class="text-center">
                    {{ instance.date|date:"Y-m-d" }}
                </td>

                {# Release Date #}
                <td class="text-center">
                    {{ instance.releaseDate|date:"Y-m-d" }}
                </td>

                {# Decade #}
                <td class="text-center">
                    {{ instance.decade }}
                </td>

                {# MPA #}
                <td class="text-center">
                    {{ instance.MPA|default:""}}
                </td>

                {# IMDB #}
                <td class="text-center text-body-secondary">
                    {{ instance.IMDB|default:""}}
                </td>

                {# TMDB #}
                <td class="text-center text-body-secondary">
                    {{ instance.TMDB|default:""}}
                </td>

                {# MC #}
                <td class="text-center text-body-secondary">
                    {{ instance.MC|default:""}}
                </td>

                {# RTCritic #}
                <td class="text-center text-body-secondary">
                    {{ instance.RTCritic|default:""}}
                </td>

                {# RTUser #}
                <td class="text-center text-body-secondary">
                    {{ instance.RTUser|default:""}}
                </td>

                {# LBXD #}
                <td class="text-center text-body-secondary">
                    {{ instance.LBXD|default:""}}
                </td>

                {# Average Rating #}
                <td class="text-center">
                    {% if instance.avg_critical_rating %}
                        {% include "./elements/badge-secondary.html" with text=instance.avg_critical_rating|convert_to_rating color="dark" fw="normal" mb="0" %}
                    {% endif %}
                </td>

                {# Oscars #}
                <td class="text-center">
                    {% if instance.watchlistaward_set.all %}
                        {% include "./elements/oscar-badge.html" with text=instance.watchlistaward_set.all|parse_oscar num=instance.watchlistaward_set.all|length icon="bi-trophy" color="gold" mb="0" %}
                    {% endif %}
                </td>
                
                <td>{% for actor in instance.cast.all %}{{actor.name|striptags}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                <td>{% for director in instance.director.all %}{{director.name|striptags}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                <td>{% for genre in instance.genres.all %}{{genre.name|striptags}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                <td>{% for company in instance.prodCompany.all %}{{company.name|striptags}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                <td>{% for prov in instance.provider.all %}{{prov.name|striptags}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
            </tr>
        {% endfor %}
    </table>
</div>

watchlist/templates/watchlist/watchlist.html
{% extends 'watchlist/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'watchlist/css/table.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchpanes/2.2.0/css/searchPanes.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchpanes/2.2.0/css/searchPanes.bootstrap5.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.7.0/css/select.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/use-bootstrap-tag@2.2.0/dist/use-bootstrap-tag.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'watchlist/css/table.css' %}">
{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/searchpanes/2.2.0/js/dataTables.searchPanes.min.js"></script>
    <script src="https://cdn.datatables.net/searchpanes/2.2.0/js/searchPanes.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.7.0/js/dataTables.select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.13.7/sorting/natural.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/use-bootstrap-tag@2.2.0/dist/use-bootstrap-tag.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'watchlist/js/watchlist.js' %}"></script>
{% endblock %}
{% block content %}
<div id="container" class="container-fluid" style="display:none">
    <div class="row g-3 mt-1">

        <div class="col-md-3">
            <div id="sidebar" class="sidebar">
                <div class="card rounded-4">
                    <div class="card-header">
                        <div id="sidebar-header" class="row">
                        </div>
                    </div>
                    <div class="card-body py-0">
                        <div class="dtsp-verticalContainer">
                            <div id="searchPanes" class="dtsp-verticalPanes">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-9">
            <div class="row g-3 mb-3">
                <div class="col-md-12">
                    <div class="card rounded-4">
                        <div class="card-body p-0">
                            <div class="d-grid gap-2 mx-auto">

                                <button class="btn btn-dark shadow text-body-secondary roboto fw-semibold rounded-4" type="button" data-bs-toggle="collapse" data-bs-target="#formCollapse" aria-expanded="false" aria-controls="formCollapse" role="button" id="collapseButton">
                                    <span id="collapseIcon" class="bi bi-plus-circle"></span>
                                    Add to Watchlist
                                </button>
                            </div>

                            {# Collapsed Form #}
                            <div class="collapse px-3 pb-3" id="formCollapse">
                                <form id="watchlistInput" method="post" action="{% url 'watchlog' %}">

                                    {% csrf_token %}
                                    {# Form Inputs #}
                                    <div class="row mt-1 g-3">
                                        <div class="col-md-1">
                                            <div id="moviePosterContainer" class="d-flex align-items-center justify-content-center bg-transparent text-body-primary h-100 border rounded-4">
                                                <i class="bi bi-film" style="font-size: 2em; color: #6c757d;"></i>
                                            </div>
                                        </div>

                                        <div class="col-md-11">

                                            {# Top Row of Inputs #}
                                            <div class="row g-3 py-1">

                                                {# Title / Fav Input #}
                                                <div class="col-md-4 form-group">
                                                    <small>

                                                        {# Form Label #}
                                                        {% include "./elements/form-label.html" with id="id_title" text="Title" icon="bi-film" %}

                                                        {# Input Group #}
                                                        <div class="input-group">

                                                            {# Title #}
                                                            <input type="text" name="title" id="id_title" class="form-control bg-transparent text-body-primary rounded-start-4">

                                                            {# Favorite #}
                                                            <input type="hidden" id="likeInput" name="favorite">
                                                            <button type="button" id="likeButton" class="btn btn-sm btn-outline-secondary text-center text-body-red rounded-end-2">
                                                                <i id="heart-icon" class="bi bi-heart"></i>
                                                            </button>

                                                        </div>

                                                    </small>
                                                </div>

                                                {# Year #}
                                                <div class="col-md-4 form-group">
                                                    <small>

                                                        {# Form Label #}
                                                        {% include "./elements/form-label.html" with id="id_year" text="Year" icon="bi-calendar2" %}

                                                        {# Year #}
                                                        <input type="text" name="year" id="id_year" class="form-control bg-transparent rounded-4 text-body-primary" placeholder="YYYY">

                                                    </small>
                                                </div>

                                                {# Date #}
                                                <div class="col-md-4 form-group">
                                                    <small>

                                                        {# Form Label #}
                                                        {% include "./elements/form-label.html" with id="id_date_added" text="Date Seen" icon="bi-calendar2-date" %}
                                                        
                                                        {# Date #}
                                                        <input type="date" name="date_added" id="id_date_added" class="form-control bg-transparent rounded-4 text-body-primary" placeholder="YYYY-MM-DD">

                                                    </small>
                                                </div>

                                                
                                            </div>

                                            <div class="row g-3 py-1">

                                                {# Tags #}
                                                <div class="col-md-12 form-group">
                                                    <small>

                                                        {# Form Label #}
                                                        {% include "./elements/form-label.html" with id="id_tags" text="Tags" icon="bi-tags" %}

                                                        {# Tag Input #}
                                                        <input name="tags" id="id_tags" type="text" class="form-control bg-transparent rounded-4 text-body-primary" placeholder="Add a tag then press Comma or Enter" >

                                                    </small>
                                                </div>

                                            </div>
       
                                        </div>
                                    </div>

                                    {# Submit Button #}
                                    <div class="row mt-3">
                                        <div class="col-md-12">
                                            <div class="d-grid gap-2 col-1 me-auto">
                                                <button class="btn btn-sm btn-secondary shadow fw-semibold raleway rounded-pill" type="submit" id="submitButton">
                                                    <span>
                                                        <div id="submitText">
                                                            Submit
                                                        </div>
                                                        <div class="d-none" id="loadingSpinner">
                                                            <span>
                                                                <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
                                                                <span role="status">Loading...</span>
                                                            </span>
                                                        </div>
                                                    </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>

                                </form>     
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Bootstrap alert -->
            <div class="alert alert-success alert-dismissible fade show d-none" role="alert" id="successAlert">
                Operation successful!
            </div>
            <div id="tableContainer">
                {% include "./watchlist-table.html" with data=data %}
            </div>
        </div>
    </div>
</div>
{% endblock %}